### ISSUE TITLE
Script does not work with config profile + credential 

### ISSUE THREAD

**Issue by juhamust** [marcincuber/aws-cfm-utils#23]
I have following configuration:

**.aws/config**
```
[profile foo-test]
role_arn = arn:aws:iam::123123:role/foo-developer
source_profile = foo-adfs
region = eu-west-1
```

**.aws/credentials**
```
[foo-adfs]
output = json
region = eu-west-1
aws_access_key_id = xyz
aws_secret_access_key = abcd
aws_session_token = foobar
```

When trying to run command like `aws-cfm-utils --profile=foo-test` the auth fails. If I copy the contents of `foo-adfs` --> `foo-test` in credentials file, it works. Running the command `aws-cfm-utils --profile=foo-adfs` without any file modifications does not work either.

Is this expected and can it be fixed?

**Comment by marcincuber** [comment]
So this could be an interesting exercise. I will look into it at some point. Few notes;
1. Those are temporary credentials created after assuming a role. I try to stay away from putting it into my .aws/* files. 
2. I am using -> [assume-role cli](https://github.com/remind101/assume-role) to assume a role which exports key, secret key and session token as global variables. In my opinion this is a lot better solution since you don't have to store outdated credentials.
3. I believe exporting those credentials as environment variables should work, perhaps test and let me know.
4. I hope I can fix it so that it handles temporary profile credentials from the file.

**Comment by marcincuber** [comment]
So in the cli I am simply running; 
```
options.credentials = new AWS.SharedIniFileCredentials({profile: args.profile});
```
and just by looking at the [aws docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) it doesn't seem like profile is meant to handle temp credentials as you described.

**Comment by marcincuber** [comment]
I believe solution to your problem is part of v1.7.0 release so just download the latest npm also read -> [Readme mfa](https://github.com/marcincuber/aws-cfm-utils#mfa)
